// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
using Avro;
using Avro.Specific;

namespace Avro.Autofill.Tests.AvroGen.AvroGenPerson;

public class Person : ISpecificRecord
{
	public static Schema _SCHEMA = Schema.Parse(
		"{\"type\":\"record\",\"name\":\"Person\",\"namespace\":\"Avro.Autofill.Tests\",\"fields\":[{\"n" +
		"ame\":\"Age\",\"type\":\"int\"},{\"name\":\"UnsignedAge\",\"type\":\"int\"},{\"name\":\"LongValue\"" +
		",\"type\":\"long\"},{\"name\":\"UnsignedLongValue\",\"type\":\"long\"},{\"name\":\"Height\",\"typ" +
		"e\":\"float\"},{\"name\":\"Weight\",\"type\":\"double\"},{\"name\":\"Salary\",\"type\":\"double\"}," +
		"{\"name\":\"IsActive\",\"type\":\"boolean\"},{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"Pr" +
		"ofilePicture\",\"type\":\"bytes\"},{\"name\":\"BirthDate\",\"type\":{\"type\":\"long\",\"logical" +
		"Type\":\"timestamp-millis\"}},{\"name\":\"CreatedAt\",\"type\":{\"type\":\"long\",\"logicalTyp" +
		"e\":\"timestamp-millis\"}},{\"name\":\"Id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid" +
		"\"}},{\"name\":\"OptionalAge\",\"type\":[\"null\",\"int\"]},{\"name\":\"OptionalWeight\",\"type\"" +
		":[\"null\",\"double\"]},{\"name\":\"OptionalSalary\",\"type\":[\"null\",\"double\"]},{\"name\":\"" +
		"OptionalFlag\",\"type\":[\"null\",\"boolean\"]},{\"name\":\"OptionalDate\",\"type\":[\"null\",{" +
		"\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}]},{\"name\":\"OptionalId\",\"type\":[\"" +
		"null\",{\"type\":\"string\",\"logicalType\":\"uuid\"}]},{\"name\":\"Scores\",\"type\":{\"type\":\"" +
		"array\",\"items\":\"int\"}},{\"name\":\"Tags\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}," +
		"{\"name\":\"Hobbies\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"Skills\",\"ty" +
		"pe\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"Ratings\",\"type\":{\"type\":\"array\"," +
		"\"items\":\"int\"}},{\"name\":\"Achievements\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}" +
		",{\"name\":\"Measurements\",\"type\":{\"type\":\"array\",\"items\":\"double\"}},{\"name\":\"Metad" +
		"ata\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"Stats\",\"type\":{\"type\":\"ma" +
		"p\",\"values\":\"int\"}},{\"name\":\"Gender\",\"type\":{\"type\":\"enum\",\"name\":\"GenderEnum\",\"" +
		"namespace\":\"Avro.Autofill.Tests\",\"symbols\":[\"Male\",\"Female\",\"Other\"]}},{\"name\":" +
		"\"OptionalGender\",\"type\":[\"null\",\"GenderEnum\"]},{\"name\":\"HomeAddress\",\"type\":{\"ty" +
		"pe\":\"record\",\"name\":\"Address\",\"namespace\":\"Avro.Autofill.Tests\",\"fields\":[{\"nam" +
		"e\":\"Street\",\"type\":\"string\"},{\"name\":\"City\",\"type\":\"string\"},{\"name\":\"ZipCode\",\"" +
		"type\":\"string\"}]}},{\"name\":\"OfficeAddress\",\"type\":[\"null\",\"Address\"]},{\"name\":\"P" +
		"reviousAddresses\",\"type\":{\"type\":\"array\",\"items\":\"Address\"}},{\"name\":\"AddressBoo" +
		"k\",\"type\":{\"type\":\"map\",\"values\":\"Address\"}}]}");

	public virtual Schema Schema { get; } = _SCHEMA;

	public int Age { get; set; }

	public int UnsignedAge { get; set; }

	public long LongValue { get; set; }

	public long UnsignedLongValue { get; set; }

	public float Height { get; set; }

	public double Weight { get; set; }

	public double Salary { get; set; }

	public bool IsActive { get; set; }

	public string Name { get; set; }

	public byte[] ProfilePicture { get; set; }

	public DateTime BirthDate { get; set; }

	public DateTime CreatedAt { get; set; }

	public Guid Id { get; set; }

	public Int32? OptionalAge { get; set; }

	public Double? OptionalWeight { get; set; }

	public Double? OptionalSalary { get; set; }

	public Boolean? OptionalFlag { get; set; }

	public DateTime? OptionalDate { get; set; }

	public Guid? OptionalId { get; set; }

	public IList<Int32> Scores { get; set; }

	public IList<String> Tags { get; set; }

	public IList<String> Hobbies { get; set; }

	public IList<String> Skills { get; set; }

	public IList<Int32> Ratings { get; set; }

	public IList<String> Achievements { get; set; }

	public IList<Double> Measurements { get; set; }

	public IDictionary<string,String> Metadata { get; set; }

	public IDictionary<string,Int32> Stats { get; set; }

	public Tests.GenderEnum Gender { get; set; }

	public Tests.GenderEnum? OptionalGender { get; set; }

	public Tests.Address HomeAddress { get; set; }

	public Tests.Address OfficeAddress { get; set; }

	public IList<Tests.Address> PreviousAddresses { get; set; }

	public IDictionary<string,Tests.Address> AddressBook { get; set; }

	public virtual object Get(int fieldPos)
	{
		switch (fieldPos)
		{
			case 0: return Age;
			case 1: return UnsignedAge;
			case 2: return LongValue;
			case 3: return UnsignedLongValue;
			case 4: return Height;
			case 5: return Weight;
			case 6: return Salary;
			case 7: return IsActive;
			case 8: return Name;
			case 9: return ProfilePicture;
			case 10: return BirthDate;
			case 11: return CreatedAt;
			case 12: return Id;
			case 13: return OptionalAge;
			case 14: return OptionalWeight;
			case 15: return OptionalSalary;
			case 16: return OptionalFlag;
			case 17: return OptionalDate;
			case 18: return OptionalId;
			case 19: return Scores;
			case 20: return Tags;
			case 21: return Hobbies;
			case 22: return Skills;
			case 23: return Ratings;
			case 24: return Achievements;
			case 25: return Measurements;
			case 26: return Metadata;
			case 27: return Stats;
			case 28: return Gender;
			case 29: return OptionalGender;
			case 30: return HomeAddress;
			case 31: return OfficeAddress;
			case 32: return PreviousAddresses;
			case 33: return AddressBook;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
		};
	}
	public virtual void Put(int fieldPos, object fieldValue)
	{
		switch (fieldPos)
		{
			case 0: Age = (Int32)fieldValue; break;
			case 1: UnsignedAge = (Int32)fieldValue; break;
			case 2: LongValue = (Int64)fieldValue; break;
			case 3: UnsignedLongValue = (Int64)fieldValue; break;
			case 4: Height = (Single)fieldValue; break;
			case 5: Weight = (Double)fieldValue; break;
			case 6: Salary = (Double)fieldValue; break;
			case 7: IsActive = (Boolean)fieldValue; break;
			case 8: Name = (String)fieldValue; break;
			case 9: ProfilePicture = (Byte[])fieldValue; break;
			case 10: BirthDate = (DateTime)fieldValue; break;
			case 11: CreatedAt = (DateTime)fieldValue; break;
			case 12: Id = (Guid)fieldValue; break;
			case 13: OptionalAge = (Int32?)fieldValue; break;
			case 14: OptionalWeight = (Double?)fieldValue; break;
			case 15: OptionalSalary = (Double?)fieldValue; break;
			case 16: OptionalFlag = (Boolean?)fieldValue; break;
			case 17: OptionalDate = (DateTime?)fieldValue; break;
			case 18: OptionalId = (Guid?)fieldValue; break;
			case 19: Scores = (IList<Int32>)fieldValue; break;
			case 20: Tags = (IList<String>)fieldValue; break;
			case 21: Hobbies = (IList<String>)fieldValue; break;
			case 22: Skills = (IList<String>)fieldValue; break;
			case 23: Ratings = (IList<Int32>)fieldValue; break;
			case 24: Achievements = (IList<String>)fieldValue; break;
			case 25: Measurements = (IList<Double>)fieldValue; break;
			case 26: Metadata = (IDictionary<string,String>)fieldValue; break;
			case 27: Stats = (IDictionary<string,Int32>)fieldValue; break;
			case 28: Gender = (Tests.GenderEnum)fieldValue; break;
			case 29: OptionalGender = fieldValue == null ? null : (Tests.GenderEnum)fieldValue; break;
			case 30: HomeAddress = (Tests.Address)fieldValue; break;
			case 31: OfficeAddress = (Tests.Address)fieldValue; break;
			case 32: PreviousAddresses = (IList<Tests.Address>)fieldValue; break;
			case 33: AddressBook = (IDictionary<string,Tests.Address>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
		};
	}
}